project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!archive/"

website:
  title: "[train]{.train}[OME]{.ome}"
  navbar:
    background: "#E2DDD1"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Ongoing projects
      - text: "Resources"
        menu:
          - href: protocols.qmd
            text: "Protocols"
          

format:
  html:
    theme: 
      - cosmo
      - styles/styles.scss
    toc: true



