---
title: "Extraction of RNA and protein from muscle tissue"
date: "Version 2019-11-11"
output: html_document
---

## Background
The Trizol-protocol can be used to extract RNA, DNA and protein from muscle tissue. The protein pellet is hard to dissolve, Kopec et al. [^a] provided guidelines for improved solubility of the protein pellet after precipitation. 
The total RNA content per tissue weight can be used as proxy marker for ribosome content. If this is an aim, care must be taken to assure e.g. no sample loss. 
External reference genes can be used to control for tissue weight.  

[^a]: Kopec, A.M., et al., Optimized solubilization of TRIzol-precipitated protein permits Western blotting analysis to maximize data available from brain tissue. Journal of neuroscience methods, 2017. 280: p. 64-76.

## Materials
For extraction of RNA and protein per sample:

* 1.5 ml Eppendorf tube with 0.5 mm RNase-free Zirconium beads (~50 ul) Keep out DNA RNAse contaminations (Eppendorf safe-lock for use in bullet blender.
* 1.5 ml tube for RNA precipitation
* 1.5 ml tube for RNA quantification (1:5 dilution, add 20 ul of DEPC-water)
* 1.5 ml tubes for Protein precipitation
* 1.5 ml tubes for Soluble protein fraction
* 1.5 ml tubes for protein quantification (1:10 dilution, add 36 ul of ddH2O)

## Solutions and chemicals
* Trizol (Life-technologies)
* Chloroform
* Isopropanol
* External reference gene (e.g. Takara lambda)
* 100% EtOH
* 95% EtOH
* 75% EtOH (kept on -20)

* Kopec buffer:

|Component     |MW	|Final concentration   |For 200 ml |
|--------------|--------|----------------------|-----------|
|EDTA	|372.24	|20 mM	|1.49 g|
|NaCl	|58.44	|140 mM	|1.64 g|
|SDS	|	|5%	|10 g|
|Tris 	|121.14	|10 mM	|2.42 g|

Adjust pH to 8.0, add phosphatase and protease inhibitors prior to use.




## Methods

### Homogenization and phase separation
1. Add 1 sample volume of beads and 300 ul Trizol to eppendorf 1.5 ml tubes. Keep on ice.
OPTIONAL: If external reference gene is used, add 1 unit to every extraction with Trizol in first step. Lambda (0.04 ng/ul, 2 ul per extraction)
2. Add frozen muscle samples (protocol optimized for 5-25 ug of wet weight muscle sample) without thawing and put tubes in Bullet blender
3. Run Bullet Blender (BB) for 1 min at speed 10, put samples on ice for 1 min. Run samples for 1 min at speed 12. Check samples, if not dissolved run until fully homogenized. 
4. Add Trizol (700 ul) to total volume 1000 ul, run samples in BB for 1 min speed 3.
5. Incubate @ RT for 5 min
6. Add 200 ul chloroform, shake 15 sec, incubate for 2-3 min.
7. Spin 12000g, 15min, 4°C
8. Pipette 450 ul of the aqueous phase to a new tube. Be careful not to disrupt the interphase or organic phase. Add 500 ul of isopropanol to precipitate RNA, incubate over night at -20°C or 10 min at room temp and continue with RNA extraction.
9. Completely remove the remaining aqueous phase, either store remaining phases at -20°C until protein extraction or continue right away


### RNA extraction
Precipitation and wash

1. Spin the isopropanol/water phase 12000g, 10min, 4°C. A pellet should form, decant supernatant, spin briefly and remove remaining liquids.
2. Add 1000 ul 75% EtOH (-20°C) @ RT, vortex gently. Spin 7500g, 5min, 4°C.
3. Repeat step 2 two more times.
4. Remove all EtOH, air dry the pellet up to 10 min with tubes upside-down. Do not over-dry!

#### Suspension

1. Add 20-40 ul of 1x DEPC-treated water (55°C), incubate at 55°C for 10min. 
2. Aliquot:
    * 5 ul to 20 ul TE  buffer for Nanodrop/Qubit[^1]
    * x ul in stock solution

[^1]: TE buffer can be used to get more reliable quality readings as pH of the buffer affects the 260 reading in the spectrometer

3. Store RNA stock solution @ -80°C.

### Protein extraction

#### DNA precipitation, protein precipitation

1. Add 300 ul of 100% EtOH, invert tubes to mix. Incubate for 3 min @ RT.
2. Spinn 2000g, 5min, 4°C.
3. Transfer the phenol-ethanol supernatant to a new tube[^2]. 
4. Transfer-volume   $\frac{1.75}{MW/950}$ , where MW is muscle weight[^3].

[^2]: Multiple aliquots are recommended, e.g. continue with two and keep two as backup on -20°C.
[^3]: Transfers a volume corresponding to 1.75 mg of tissue

5. Add at least 2x isopropanol, shake and incubate samples @ RT, 10 min.
6. Spinn 12 000g, 10 min, 4°C
7. Wash pellet in 500 ul 95% EtOH. Work quickly do not dry out the pellet, no incubations. Dislodge the pellet from the tube in every wash. 
8. Spinn, 7500 g, 5 min, 4°C. Remove wash. 
9. Repeat step 7-8, one to two more times. 
10. Air dry pellet 5-10 min, do not dry out the pellet but remove ALL EtOH! (Centrifuge briefly to remove all EtOH).

#### Protein re-suspension

1. Add 45 ul of Kopec-buffer
2. Incubate 2-4 hours at 50°C
3. Pipette solution to mix. Centrifuge at room temp to sediment any insoluble material. (10000 g, 5 min)
4. Transfer supernatant to 3 aliquots (~60 ul) + 4 ul to 36 ul H2O for 1:10 dilution
5. Measure 5 ul of 1:10 dilution in qubit for protein concentration. Store at -80°C







