---
title: "General purpose muscle tissue homogenization protocol"
date: "Version 2019-11-12"
output: html_document
---

## Background and purpose

Skeletal muscle tissue can be homogenized using mechanical disruption together with a suitable buffer solution to produce a lysate for protein analysis. The choice of buffer will significantly affect the ability to detect specific proteins in the lysate. This protocol details a general purpose tissue homogenization.

## Materials

* Microfuge tubes (1.5 ml Eppendorf)
* Plastic pestle
* Centrifuge (capable of 10 000 g and 4°C)
* Ice
* Lysis buffer (e.g. Hepes-buffer, Ripa-buffer)

## Methods

1. Prepare the tissue by dissection away any connective tissue and blood. If you are working with wet tissue, this step should be done prior to freezing. Freeze dried tissue can be dissected in room temperature under the microscope. Use 10-50 mg wet-weight tissue or 2-10 mg freeze-dried tissue.
2. Add protease/phosphatase inhibitors to the ice-cold lysis buffer.
3. Keep the sample on dry ice or cooling block until you add the ice cold lysis buffer of choice. Use 20 ul/mg wet-weight or 80  ul/mg dry weight. 
4. Quickly disrupt the tissue by hand using the plastic pestle until there are no visible pieces.
5. Keep the sample on ice, vortex or rotate the sample for 20-60 min. 
6. Spin the sample 10 min, 10 000 g, 4°C
7. Carefully remove the supernatant to a new tube without disrupting the pellet. 
8. Aliquot the sample to a tube for protein concentration determination (1:10 dilution, 4 ul to 36 ul ddH2O. Keep a known volume for later normalization of the protein concentration (e.g. to 3 ug/ul) keep on ice.
